config/routes.rb
Rank::Application.routes.draw do
  resources :commits


  resources :projects


  devise_for :members, :controllers => { :omniauth_callbacks => "members/omniauth_callbacks" }  
  

   root :to => 'homes#index'
end

app/models/commit.rb
class Commit < ActiveRecord::Base
  attr_accessible :commit_date, :committer_email, :committer_name, :html_url, :project_id, :sha, :project, :author_date, :author_name, :author_email
  belongs_to :project

  def self.get_commit_from repo
    @client = Octokit::Client.new(:login => "ken0", :password => "password9")
    all_commits = []
    commits = Array.new(100)
    last_commit =  @client.commits("#{repo.owner.login}/#{repo.name}").first
    begin
      commits = @client.commits("#{repo.owner.login}/#{repo.name}", 'master', {per_page: 100, sha: last_commit.sha})
      last_commit = commits.last
      all_commits += commits
    end until commits.count < 100
    all_commits.each{|commit| create_or_update(commit, repo)}
  end

  protected
  def self.create_or_update commit, repo
    local_commit = Commit.find_or_create_by_sha commit.sha
    local_commit.update_attributes(
      author_date: commit.commit.author.date,
      author_email: commit.commit.author.email,
      author_name: commit.commit.author.name,
      commit_date: commit.commit.committer.date,
      committer_email: commit.commit.author.email,
      committer_name: commit.commit.author.name,
      html_url: commit.html_url,
      project: Project.find_by_uid(repo.id)#should be project_id
    )
  end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  # GET /commits
  # GET /commits.json
  def index
    @commits = Commit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @commits }
    end
  end

  # GET /commits/1
  # GET /commits/1.json
  def show
    @commit = Commit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @commit }
    end
  end

  # GET /commits/new
  # GET /commits/new.json
  def new
    @commit = Commit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @commit }
    end
  end

  # GET /commits/1/edit
  def edit
    @commit = Commit.find(params[:id])
  end

  # POST /commits
  # POST /commits.json
  def create
    @commit = Commit.new(params[:commit])

    respond_to do |format|
      if @commit.save
        format.html { redirect_to @commit, notice: 'Commit was successfully created.' }
        format.json { render json: @commit, status: :created, location: @commit }
      else
        format.html { render action: "new" }
        format.json { render json: @commit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /commits/1
  # PUT /commits/1.json
  def update
    @commit = Commit.find(params[:id])

    respond_to do |format|
      if @commit.update_attributes(params[:commit])
        format.html { redirect_to @commit, notice: 'Commit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @commit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commits/1
  # DELETE /commits/1.json
  def destroy
    @commit = Commit.find(params[:id])
    @commit.destroy

    respond_to do |format|
      format.html { redirect_to commits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/views/commits/_form.html.slim
= form_for @commit do |f|
  - if @commit.errors.any?
    #error_explanation
      h2 = "#{pluralize(@commit.errors.count, "error")} prohibited this commit from being saved:"
      ul
        - @commit.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :sha
    = f.text_field :sha
  .field
    = f.label :html_url
    = f.text_field :html_url
  .field
    = f.label :author_id
    = f.text_field :author_id
  .field
    = f.label :author_login
    = f.text_field :author_login
  .field
    = f.label :commit_date
    = f.text_field :commit_date
  .field
    = f.label :committer_name
    = f.text_field :committer_name
  .field
    = f.label :committer_email
    = f.text_field :committer_email
  .field
    = f.label :project_id
    = f.number_field :project_id
  .actions = f.submit 'Save'

app/views/commits/edit.html.slim
h1 Editing commit

== render 'form'

= link_to 'Show', @commit
'|
= link_to 'Back', commits_path

app/views/commits/index.html.slim
h1 Listing commits

table
  tr
    th Sha
    th Html url
    th Author
    th Author login
    th Author date
    th Committer name
    th Committer email
    th Project
    th
    th
    th

  - @commits.each do |commit|
    tr
      td = commit.sha
      td = commit.html_url
      td = commit.author_id
      td = commit.author_login
      td = commit.commit_date
      td = commit.committer_name
      td = commit.committer_email
      td = commit.project_id
      td = link_to 'Show', commit
      td = link_to 'Edit', edit_commit_path(commit)
      td = link_to 'Destroy', commit, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Commit', new_commit_path

app/views/commits/new.html.slim
h1 New commit

== render 'form'

= link_to 'Back', commits_path

app/views/commits/show.html.slim
p#notice = notice

p
  strong Sha:
  = @commit.sha
p
  strong Html url:
  = @commit.html_url
p
  strong Author:
  = @commit.author_id
p
  strong Author login:
  = @commit.author_login
p
  strong Author date:
  = @commit.commit_date
p
  strong Committer name:
  = @commit.committer_name
p
  strong Committer email:
  = @commit.committer_email
p
  strong Project:
  = @commit.project_id

= link_to 'Edit', edit_commit_path(@commit)
'|
= link_to 'Back', commits_path