config/routes.rb
Rank::Application.routes.draw do
  resources :commits


  resources :projects


  devise_for :members, :controllers => { :omniauth_callbacks => "members/omniauth_callbacks" }  
  

   root :to => 'homes#index'
end

app/views/layouts/_flash.html.erb
<div class="wrapper">
	<% flash.each do |type, message| %>
	  <div class="alert <%= bootstrap_class_for(type) %> fade in">
	    <button class="close" data-dismiss="alert">×</button>
	    <%= message %>
	  </div>
	<% end %>
</div>

app/views/layouts/_user_header.html.slim
header.navbar-wrapper
    div.container
        - if current_member
            | Logged in as 
            span 
                = current_member.email
                = link_to " Log Out", destroy_member_session_path , :method => :delete
        - else
            ul.nav
                li 
                    = link_to "Sign in with github",member_omniauth_authorize_path(:github)
                li
                    = link_to "Sign up",new_member_registration_path
                | or 
                li
                    = link_to "Log In",new_member_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rank</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="user_header">
      <%= render :partial=>'layouts/user_header' %>
  </div>

  <div class="container">
    <%= render 'layouts/flash' ,flash:flash unless flash.blank?%>
    <div>
      <a href="https://github.com/bay6/rank_of_github2"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png" alt="Fork me on GitHub"></a>

    <%= yield %>

    </div>
  </div>

</body>
</html>